import { Metadata } from "next";
import styles from "../styles/notfound.module.css";
import Link from "next/link";

export const metadata:Metadata = {
  title: "404 Not Found",
  description: 'Generated by Next.js',
}

export default function NotFound() {
  return <div className={styles.container}>
    <img className={styles.img} src="/img/notfound/notfound.webp" />
    <h1 className="f-display">404 Not found!</h1>
    <p>페이지를 찾을수 없습니다.</p>
    <Link href={'/'}>홈페이지로 이동</Link>
  </div>
}